[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "board"
version = "1.1"
authors = [
  { name="Tim Golden", email="mail@timgolden.me.uk" },
]
description = "A standard Board mechanism for Dojo tasks"
readme = "README.rst"
requires-python = ">=3.2"
license = "MIT"

[project.urls]
Homepage = "https://github.com/tjguk/dojo-board"

[tool.setuptools]
py-modules = ["board"]
